# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Multipeer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.0.1'
  pod 'Bond', '~> 7.6.1'

end
